#region Copyright (c) 2015-2018 Visyn
//The MIT License(MIT)
//
//Copyright (c) 2015-2018 Visyn
//
//Permission is hereby granted, free of charge, to any person obtaining a copy
//of this software and associated documentation files (the "Software"), to deal
//in the Software without restriction, including without limitation the rights
//to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//copies of the Software, and to permit persons to whom the Software is
//furnished to do so, subject to the following conditions:

//The above copyright notice and this permission notice shall be included in all
//copies or substantial portions of the Software.

//THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//SOFTWARE.
#endregion
#region Autogenerated T4 Text Template
// Autogenerated from T4 Text Template :	Max.tt
//											file:\C:\Customer\Lucent\Visyn.Mathematics\Lib\Max.tt
// Autogeneration date/time:				4/17/2018 4:18:33 PM
#endregion
using System;
using Visyn.Mathematics;

using System.Runtime.CompilerServices;

namespace Visyn.Mathematics 
{ 
	public static partial class Numbers
	{
		/// <summary>
	    /// Return the maximum value for the specified type
        /// </summary>
        /// <returns>Maximum value for the specified type</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static T MaxValue<T>() where T : INumeric<T>
		{ 
			if(typeof(T) == typeof(Int32)) return (T)(object)(Int32.MaxValue);
			if(typeof(T) == typeof(Int64)) return (T)(object)(Int64.MaxValue);
			if(typeof(T) == typeof(Int16)) return (T)(object)(Int16.MaxValue);
			if(typeof(T) == typeof(Char)) return (T)(object)(Char.MaxValue);
			if(typeof(T) == typeof(UInt32)) return (T)(object)(UInt32.MaxValue);
			if(typeof(T) == typeof(UInt64)) return (T)(object)(UInt64.MaxValue);
			if(typeof(T) == typeof(UInt16)) return (T)(object)(UInt16.MaxValue);
			if(typeof(T) == typeof(Byte)) return (T)(object)(Byte.MaxValue);
			if(typeof(T) == typeof(Double)) return (T)(object)(Double.MaxValue);
			if(typeof(T) == typeof(Single)) return (T)(object)(Single.MaxValue);
			if(typeof(T) == typeof(Decimal)) return (T)(object)(Decimal.MaxValue);
			throw new NotImplementedException($"{nameof(MaxValue)} not implemented for type {typeof(T).Name}");
		}
        /// <summary>
        /// Return the maximum of two values
        /// </summary>
        /// <param name="a">First value</param>
        /// <param name="b">Second value</param>
        /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Int32 Max(Int32 a, Int32 b) => a>b ? a : b;
		
	    /// <summary>
	    /// Return the maximum of two nullable values
	    /// </summary>
	    /// <param name="a">First value</param>
	    /// <param name="b">Second value</param>
	    /// <param name="defaultValue">Value to use for comparison if either of the parameters are null</param>
	    /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static Int32 Max(Int32? a, Int32? b, Int32 defaultValue=Int32.MinValue)
		{
		    var aValue = a.GetValueOrDefault(defaultValue);
		    var bValue = b.GetValueOrDefault(defaultValue);
            return aValue > bValue ? aValue : bValue;
	    }
        /// <summary>
        /// Return the maximum of two values
        /// </summary>
        /// <param name="a">First value</param>
        /// <param name="b">Second value</param>
        /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Int64 Max(Int64 a, Int64 b) => a>b ? a : b;
		
	    /// <summary>
	    /// Return the maximum of two nullable values
	    /// </summary>
	    /// <param name="a">First value</param>
	    /// <param name="b">Second value</param>
	    /// <param name="defaultValue">Value to use for comparison if either of the parameters are null</param>
	    /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static Int64 Max(Int64? a, Int64? b, Int64 defaultValue=Int64.MinValue)
		{
		    var aValue = a.GetValueOrDefault(defaultValue);
		    var bValue = b.GetValueOrDefault(defaultValue);
            return aValue > bValue ? aValue : bValue;
	    }
        /// <summary>
        /// Return the maximum of two values
        /// </summary>
        /// <param name="a">First value</param>
        /// <param name="b">Second value</param>
        /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Int16 Max(Int16 a, Int16 b) => a>b ? a : b;
		
	    /// <summary>
	    /// Return the maximum of two nullable values
	    /// </summary>
	    /// <param name="a">First value</param>
	    /// <param name="b">Second value</param>
	    /// <param name="defaultValue">Value to use for comparison if either of the parameters are null</param>
	    /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static Int16 Max(Int16? a, Int16? b, Int16 defaultValue=Int16.MinValue)
		{
		    var aValue = a.GetValueOrDefault(defaultValue);
		    var bValue = b.GetValueOrDefault(defaultValue);
            return aValue > bValue ? aValue : bValue;
	    }
        /// <summary>
        /// Return the maximum of two values
        /// </summary>
        /// <param name="a">First value</param>
        /// <param name="b">Second value</param>
        /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Char Max(Char a, Char b) => a>b ? a : b;
		
	    /// <summary>
	    /// Return the maximum of two nullable values
	    /// </summary>
	    /// <param name="a">First value</param>
	    /// <param name="b">Second value</param>
	    /// <param name="defaultValue">Value to use for comparison if either of the parameters are null</param>
	    /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static Char Max(Char? a, Char? b, Char defaultValue=Char.MinValue)
		{
		    var aValue = a.GetValueOrDefault(defaultValue);
		    var bValue = b.GetValueOrDefault(defaultValue);
            return aValue > bValue ? aValue : bValue;
	    }
        /// <summary>
        /// Return the maximum of two values
        /// </summary>
        /// <param name="a">First value</param>
        /// <param name="b">Second value</param>
        /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UInt32 Max(UInt32 a, UInt32 b) => a>b ? a : b;
		
	    /// <summary>
	    /// Return the maximum of two nullable values
	    /// </summary>
	    /// <param name="a">First value</param>
	    /// <param name="b">Second value</param>
	    /// <param name="defaultValue">Value to use for comparison if either of the parameters are null</param>
	    /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static UInt32 Max(UInt32? a, UInt32? b, UInt32 defaultValue=UInt32.MinValue)
		{
		    var aValue = a.GetValueOrDefault(defaultValue);
		    var bValue = b.GetValueOrDefault(defaultValue);
            return aValue > bValue ? aValue : bValue;
	    }
        /// <summary>
        /// Return the maximum of two values
        /// </summary>
        /// <param name="a">First value</param>
        /// <param name="b">Second value</param>
        /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UInt64 Max(UInt64 a, UInt64 b) => a>b ? a : b;
		
	    /// <summary>
	    /// Return the maximum of two nullable values
	    /// </summary>
	    /// <param name="a">First value</param>
	    /// <param name="b">Second value</param>
	    /// <param name="defaultValue">Value to use for comparison if either of the parameters are null</param>
	    /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static UInt64 Max(UInt64? a, UInt64? b, UInt64 defaultValue=UInt64.MinValue)
		{
		    var aValue = a.GetValueOrDefault(defaultValue);
		    var bValue = b.GetValueOrDefault(defaultValue);
            return aValue > bValue ? aValue : bValue;
	    }
        /// <summary>
        /// Return the maximum of two values
        /// </summary>
        /// <param name="a">First value</param>
        /// <param name="b">Second value</param>
        /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static UInt16 Max(UInt16 a, UInt16 b) => a>b ? a : b;
		
	    /// <summary>
	    /// Return the maximum of two nullable values
	    /// </summary>
	    /// <param name="a">First value</param>
	    /// <param name="b">Second value</param>
	    /// <param name="defaultValue">Value to use for comparison if either of the parameters are null</param>
	    /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static UInt16 Max(UInt16? a, UInt16? b, UInt16 defaultValue=UInt16.MinValue)
		{
		    var aValue = a.GetValueOrDefault(defaultValue);
		    var bValue = b.GetValueOrDefault(defaultValue);
            return aValue > bValue ? aValue : bValue;
	    }
        /// <summary>
        /// Return the maximum of two values
        /// </summary>
        /// <param name="a">First value</param>
        /// <param name="b">Second value</param>
        /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Byte Max(Byte a, Byte b) => a>b ? a : b;
		
	    /// <summary>
	    /// Return the maximum of two nullable values
	    /// </summary>
	    /// <param name="a">First value</param>
	    /// <param name="b">Second value</param>
	    /// <param name="defaultValue">Value to use for comparison if either of the parameters are null</param>
	    /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static Byte Max(Byte? a, Byte? b, Byte defaultValue=Byte.MinValue)
		{
		    var aValue = a.GetValueOrDefault(defaultValue);
		    var bValue = b.GetValueOrDefault(defaultValue);
            return aValue > bValue ? aValue : bValue;
	    }
        /// <summary>
        /// Return the maximum of two values
        /// </summary>
        /// <param name="a">First value</param>
        /// <param name="b">Second value</param>
        /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Double Max(Double a, Double b) => a>b ? a : b;
		
	    /// <summary>
	    /// Return the maximum of two nullable values
	    /// </summary>
	    /// <param name="a">First value</param>
	    /// <param name="b">Second value</param>
	    /// <param name="defaultValue">Value to use for comparison if either of the parameters are null</param>
	    /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static Double Max(Double? a, Double? b, Double defaultValue=Double.MinValue)
		{
		    var aValue = a.GetValueOrDefault(defaultValue);
		    var bValue = b.GetValueOrDefault(defaultValue);
            return aValue > bValue ? aValue : bValue;
	    }
        /// <summary>
        /// Return the maximum of two values
        /// </summary>
        /// <param name="a">First value</param>
        /// <param name="b">Second value</param>
        /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Single Max(Single a, Single b) => a>b ? a : b;
		
	    /// <summary>
	    /// Return the maximum of two nullable values
	    /// </summary>
	    /// <param name="a">First value</param>
	    /// <param name="b">Second value</param>
	    /// <param name="defaultValue">Value to use for comparison if either of the parameters are null</param>
	    /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static Single Max(Single? a, Single? b, Single defaultValue=Single.MinValue)
		{
		    var aValue = a.GetValueOrDefault(defaultValue);
		    var bValue = b.GetValueOrDefault(defaultValue);
            return aValue > bValue ? aValue : bValue;
	    }
        /// <summary>
        /// Return the maximum of two values
        /// </summary>
        /// <param name="a">First value</param>
        /// <param name="b">Second value</param>
        /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static Decimal Max(Decimal a, Decimal b) => a>b ? a : b;
		
	    /// <summary>
	    /// Return the maximum of two nullable values
	    /// </summary>
	    /// <param name="a">First value</param>
	    /// <param name="b">Second value</param>
	    /// <param name="defaultValue">Value to use for comparison if either of the parameters are null</param>
	    /// <returns>Maxmum value</returns>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		public static Decimal Max(Decimal? a, Decimal? b, Decimal defaultValue)
		{
		    var aValue = a.GetValueOrDefault(defaultValue);
		    var bValue = b.GetValueOrDefault(defaultValue);
            return aValue > bValue ? aValue : bValue;
	    }
 	    /// <summary>
	    /// Return the maximum of two nullable values
	    /// </summary>
	    /// <param name="a">First value</param>
	    /// <param name="b">Second value</param>
	    /// <returns>Maxmum value</returns>
		public static Decimal Max(Decimal? a, Decimal? b) => Max(a, b,Decimal.MinValue);
	}
}